apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.5.31
      helm:
        releaseName: postgres
        valueFiles:
          - $values/values.yaml
    - repoURL: "https://github.com/SP0Fs/postgres-k8s.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/SP0Fs/postgres-k8s.git"
      targetRevision: HEAD
      path: resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
