---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-synapse
  namespace: postgres
spec:
  encryptedData:
    password: AgBBlCpyKWCYO/x3QQgkD9uBSFtbcPYtOyZOEjxb37f16BgZiyFSnDMtMtOgSRYOjwTjmJbmdFNQb6H4o1bkaez16pyM76xfUra8QqflvK06Ed4MiRxqnmRfwDEg5Oi/wpE8xTXezKW9huEwSDmumg08r4vs+GfdZh4NPI53s9m0iIb0smAc2+AWhQo3WlYBfvhkSu3HoGR6DZQ/OU+aYSAKeLRbVCdRx2Ec4gRCGcd+jozWRcM+QpB7L8F0SHoTVpZM7Ypz/yOitzPkQvcBUynV8d9S1ZznpD2qNA+4irqjr0WkF1bxy07R4P/qfJIV4qH4lQv8/kvXe4ZJHODElbQelsQQVVb6niU3med8cK8SZdl/y3qShn6mkEWaGhXVXFy1gi+qr8jQHCyYYCJke3Bk6qK7gFLJh+6k1IXOFPqAor8iP/wfb6YcIEaQeEL/Ex8NQM2Xv0SpHoUDFrsku8ijZDEOSqW1BY1xqsU436NTaN/MKGJIZG0m5ABEFDqhBB/HNCJG7fySRnEs/h9bo9WdI4cg3Yk9BDRiE6UFyLF2XkxywoaeSV8ujVZksSS0tZ3/0+YDe++UqbNDDMvMppoH8WI3JcbYvQtTGDkcCoACuJtZqJT/bnHUSero0bBGLT8fPLJ0yw24Lf4klh7E99rqJEZAWaXhiAMBxvAuYymxjifNPp68sPLxXHXVHnmeJg7GJq+/LCcHawEkuTkGIk/2Xm7kbQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-synapse
      namespace: postgres
    type: Opaque
