---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-homeassistant
  namespace: postgres
spec:
  encryptedData:
    password: AgBJ8T0g6nceJvhA7E81W6hpVxKeFd+/ZcIi0FNmhJfDAdU+4i14PCeISe2hPC6s5LRRbn1wY8Mtdpe7p5XuhE/n/6w4CXPBgE5rzxxKsNaSicbENEYjKE1WCV1LNjlhotrIJWipe7SHVRL7SWfs1hsBdEIDKXGrpOfa89isY3AvXKMGSYvEfWsJNCK+wUw8BPNmVczQc9mLpdyY3+DKFMqnaLQaXa4eBwOYqs0zvVlVzG+WZhJp6QU7jS0avpLMJe6S6Nk1QfYqePJ3HJipUK6A++p1hV8+PUNWJBtrysAMB5KpiLTAPggIJbTDc8FcFYZbizJ0llsqLW/E0+IR/r/IAMT9ePaVZ1XzZDL+UM2xr5V+V4nrVz2s5wqWjQ1BFWwYmJ/Mu8dNXgi9dNCkYvJVvsN6BdV5nnUQAO2HZsEdb5o4wLzzkqlTvXE2hpIo5RN3ScInpOOIRGHgDLHcBix5ELSI8BnqxVedobhkg2QPWEeLrByPe7b/bwI3bIKjZoTASlBrTwGAGykkB2OTUW5GZKheThihhAkq/Z5RE5EnSiV46Qqkk+W8hCm0lfx459J64o7HsrmfQG1ytgg6tB2TbwTpvctFxz6A0KPfUjumkUcf/akAREjBhJC+sarYfBZeo5S3dG6fQqoNYgoGn7pAKCmqcPD+2wrXZfXBruF4KnfgGFD8D9WGQpouPZKlFf9W9PLMnYAEYBdpVKWUSzJnMeuGwYnSQ03kWpGbP9Awhg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-homeassistant
      namespace: postgres
    type: Opaque
